### ISSUE TITLE
vtm panel

### ISSUE THREAD

**Issue by Vosjedev** [directvt/vtm#397]
Hi!

I started making an info panel for vtm, github repo is [here](https://github.com/Vosjedev/vtm-panel/).
I made this issue to update on progress.

**Comment by Vosjedev** [comment]
Currently this has the issue that when using it, the panel resets the escape code, which leads to vtm sometimes drawing the panel background color instead of the default color, and the terminal is really gliched. I made a video of it:

https://github.com/netxs-group/vtm/assets/100359465/9813d666-f7a0-4575-b6df-74955d315ec2

**Comment by Vosjedev** [comment]
I made it check the vtm version, because originaly it was at the bottom, covering the vtm version at the bottom right.

**Comment by Vosjedev** [comment]
I am not using bash, I am using a shell called [xonsh](https://xon.sh/) because of the python/shell combi. I dont know how the coloring works, because you can insert `{color}` in the $PROMPT variable and it makes the color for you. It uses prompt_toolkit.

But I think this issue is there when I am using bash as well... Will verify in a second

**Comment by o-sdn-o** [comment]
Sorry for the slow replies, I've been diving into extending the `win32-input-mode` protocol and this will take some time.

**Comment by o-sdn-o** [comment]
I am planning to add an extra section to the user's viewport to bind an external panel like yours there. This is a one cell high (adjustable value) and full screen width section located at the very top of the vtm viewport.

**Comment by o-sdn-o** [comment]
vtm will output whatever your panel prints to the console.

**Comment by Vosjedev** [comment]
What's the progress here? Where are you currently working on?

**Comment by o-sdn-o** [comment]
I dived into implementing full keyboard support. It is necessary to uniquely identify the pressed buttons in order to use them inside the vtm. This must be implemented for correct remote work on heterogeneous systems. For example, in a Windows-Linux remote connection scenario, keyboard input occurs with errors.

Without keyboard input working correctly, it's not worth talking about remote use via directvt.

I also found that vtm is used on Android. Keyboard control is very lacking there, because instead of a mouse there is only a touch interface.

It also requires prebuild binaries for ARM architecture, including 32-bit ones, and since vtm cannot be built on a 32-bit host, the compiler needs more than 4 gigs of RAM. I have to build such assemblies too. There were a number of issues when compiling to 32-bit architecture.

I'll be able to work on the vtm panel after I finish keyboard support, it will take some time.

**Comment by o-sdn-o** [comment]
Along the way, I make keyboard events available from outside using the vt-input-mode #400 protocol.

**Comment by Vosjedev** [comment]
> I also found that vtm is used on Android.

Yes, it is available in the termux repos. I installed it. Single clickes work, but dragging only moves the mouse, without sending  a click. I cant verify it is not getting a click, because I cant open debug mode, my tablet is to old to support the `🐞`.

>  It also requires prebuild binaries for ARM architecture, including 32-bit ones, and since vtm cannot be built on a 32-bit host, the compiler needs more than 4 gigs of RAM. I have to build such assemblies too. There were a number of issues when compiling to 32-bit architecture.

Vtm is compiled for android in the termux repo. I guess compiling works for android... but on both my android devices `uname -m` returns `aarch64`, so I guess they both are 64bit arm. Also, I once was able to run vtm on my `armv7l` raspberrypi. I just deleted it to update it, then found out I could not recompile because of outdated gcc.

**Comment by o-sdn-o** [comment]
I'm currently doing builds for ARM 32-bit and ARM 64-bit. For Windows, this turned out to be easy, now I'm doing it for Linux.

**Comment by Vosjedev** [comment]
yes I know, but what I mean, could you use the termux binary on arm linux?

It is possible responses are slow next week, I am on holydays to Spain.

**Comment by o-sdn-o** [comment]
I haven't tested this (run Android/termux binaries on Linux), I don't have ARM devices within reach yet, and I'll test it on QEMU a bit later.

Have a nice vacation!

**Comment by Vosjedev** [comment]
> I don't have ARM devices within reach yet

I am thinking about buying a pinetab 2, but I don't know if I can get it in europe yet. Pine64's site is not very clear on that...

> Have a nice vacation!

Thank you!

**Comment by Vosjedev** [comment]
I am going to revisit my panel, but first I have to chatch up on release notes: still on v0.9.9q!

**Comment by o-sdn-o** [comment]
To hide any scrollbars, the application running in the panel simply needs to switch to the alternate buffer using the following vt-sequence:
```bash
# Altbuf
printf "\e[?1049h"

# Normal scrollback
printf "\e[?1049l"
```

Thank you very much for doing this! 👍

**Comment by Vosjedev** [comment]
I guess I wrote a very detailed doc including code snippets instead. It uses examples in python3, but there's a bash adaptation at the bottom for the people that don't understand python (assuming everyone understands either python or bash :D ).
[panelDocs.md](https://github.com/netxs-group/vtm/files/13046671/panelDocs.md)

**Comment by o-sdn-o** [comment]
If you don’t mind, I’ll open a pull request (or you can open it yourself) and we’ll make edits there.

**Comment by o-sdn-o** [comment]
I edited the [panel.md](https://github.com/o-sdn-o/vtm/blob/panel-docs/doc/panel.md) text a little and added a link to it from readme.md.

**Comment by Vosjedev** [comment]
I don't have anything to add, I agree with your edits. Thanks for merging!

**Comment by Vosjedev** [comment]
I agree with closing. Note I linked this issue from the repo as status tracker for the panel I am maintaining. If you want I can move that over to there.

**Comment by o-sdn-o** [comment]
I can't translate the last sentence 😅. Perhaps we need to cross-link this, add links to `doc/panel.md` and the like.

**Comment by Vosjedev** [comment]
Ah, sorry, I meant:

I am currently asking people to go to this issue for announcements etc for [my script](https://github.com/vosjedev/vtm-panel).
If you want, I can make an issue in my own repo for announcements etc.

**Comment by o-sdn-o** [comment]
I have added a cross-reference to your vtm panel repository in the `doc/panel.md` subsection `App-based Dashboard`.

**Comment by o-sdn-o** [comment]
I've corrected the text a little. This text was slightly mismatched. I didn't notice that the link was already there in the text 😅.

**Comment by Vosjedev** [comment]
I guess I will have to redo some things on my panel anyways to make it a bit more userfriendly (add stuff like colors and a config).
Does the vtm terminal translate color escape sequences (`\e[48;2;0;0;0m`-like) to windows api calls on windows?

**Comment by o-sdn-o** [comment]
> Does the vtm terminal translate color escape sequences (\e[48;2;0;0;0m-like) to windows api calls on windows automatically?

Yes, it is supported by vtm. vtm renders everything (vt sequences, etc) onto its internal canvas, and then prints the final canvas using the Windows Console API.

**Comment by Vosjedev** [comment]
Then I'l go and add color support later. I am currently working on other stuff.
