### ISSUE TITLE
How to tell if a terminal session is in vtm?

### ISSUE THREAD

**Issue by Fan-iX** [directvt/vtm#476]
I used to check whether $VTM_CONFIG is empty to see if the session is in vtm. (An non-empty $VTM_CONFIG does not ensure a non-vtm session though)

Since $VTM_CONFIG is removed from v0.9.19, I'm no longer able to check that.

Maybe we can have something like $VTM (like $TMUX in tmux), or $VTM_LEVEL (like $SHLVL) if possible?

**Comment by o-sdn-o** [comment]
I agree, setting the $VTM variable is the right thing to do.

**Comment by o-sdn-o** [comment]
I closed everything automatically again without waiting for confirmation from you. Ask me if something doesn't work 🙏🙏🙏.
