### ISSUE TITLE
Applications launched in vtm has a `umask` of `0000`

### ISSUE THREAD

**Issue by Fan-iX** [directvt/vtm#478]
In some of my Linux systems (including wsl1, wsl2, termux and native Linux), all applications launched in a `vtm` desktop has a `umask` of `0000`, so that all files and folders I create is writable for all other users by default.

![image](https://github.com/directvt/vtm/assets/61686936/1ae0dd12-6712-47c3-8958-4bb767d7619e)

Applications launched by `vtm -r bash` inherit the `umask` value from the parent environment.

Seems the `::umask()` call in these line causes the issue.

https://github.com/directvt/vtm/blob/affcba8ec48556196247e513356b445e4f58b832/src/netxs/desktopio/system.hpp#L2328-L2336

**Comment by o-sdn-o** [comment]
Yes, that's right, this needs to be fixed.

**Comment by o-sdn-o** [comment]
I removed the umask modification at vtm server startup. Most likely it was a legacy of some ancient experiments.

**Comment by o-sdn-o** [comment]
I tested vtm on linux and macos. At first glance, everything works fine.
