### ISSUE TITLE
Escape sequenses in --version output

### ISSUE THREAD

**Issue by Vosjedev** [directvt/vtm#484]
I am trying to write a script that uses the output of `--version`. It seems like vtm prints escape sequences in the output.

I suggest one of these options:
- do not print escape sequenses in the output at all
-  detect pipes/output redirection, and do not print escape sequenses if so.

**Comment by o-sdn-o** [comment]
I suspect you catch the following sequences `\e[22;0t` and \e[23;0t:
```
root@megasus:~# echo "----"; vtm -v; echo "---"
----
v0.9.27
---
root@megasus:~# 
```

```
      852:  key: undef
      852: stdin: 
      852:      \r
      852: stdout: 
      852:      \r\n
      852:      \r
      852:      \e[?2004l\r
      852: stdout: 
      852:      ----\r\n
      852: 
      852: stdout: 
      852:      \e[22;0t
      852: stdout: 
      852:      v0.9.27\r\n
      852: 
      852: stdout: 
      852:      \e[23;0t
      852: stdout: 
      852:      ---\r\n
      852:      \e[?2004h
      852:      \e]0;root@megasus: ~\u0007root@megasus:~# 
```

**Comment by o-sdn-o** [comment]
It is a get/set terminal window title sequences. I'll remove them.

**Comment by Vosjedev** [comment]
I think you are correct on what sequences get printed (duh, you wrote the code).

>  I'll remove them.

Thank you!

**Comment by Vosjedev** [comment]
Though I would check if it was already changed in dev branch, but there is no dev branch anymore? why?

**Comment by o-sdn-o** [comment]
I commit to the https://github.com/o-sdn-o/vtm/tree/vt-input-mode branch, it is a-la dev branch.

**Comment by o-sdn-o** [comment]
In the commit header I will make a reference to this issue, it will be displayed here.

**Comment by o-sdn-o** [comment]
I fix it.
