### ISSUE TITLE
`Enter` is bind to `\C-j`(`\n`) instead of `\C-m`(`\r`) in linux `vtm` applications

### ISSUE THREAD

**Issue by Fan-iX** [directvt/vtm#500]
### Minimal reproducible example:
 - `wsl` - `bash` - `ctrl+q` - `Enter` gives `^M` after the prompt. (expected)
 - `wsl` - `vtm`(v0.9.34) - `bash` - `ctrl+q` - `Enter` gives a new line (actually a `^J`, or `ctrl+q`-`ctrl+j`) after the prompt. (unexpected)
 - `powershell` - `vtm ssh wsl vtm`(both v0.9.34) - `bash` - `ctrl+q` - `Enter` gives `^M` after the prompt. (<del>unexpectedly</del> expected)

### Why it affects

I have a

```
"\C-j":self-insert
```

in my `.inputrc`. When I type `ctrl+enter` or `ctrl+j`, it inserts a new line in the prompt line, so that I can create a multi-line prompt command. When I type `enter` or `ctrl+m`, (which sends `^M` in common cases) the command is submitted.

But now I'm no longer able to submit commands in this way.

This can be easily confirmed through a single bash command `bind '"\C-j":self-insert'`.

**Comment by o-sdn-o** [comment]
This is due to the new input parsing mechanism for Linux. I'll try to fix this. Thanks for the feedback.

**Comment by o-sdn-o** [comment]
I think I've fixed this issue. You can test it.

**Comment by Fan-iX** [comment]
Looks fine to me.

Thanks. 😄
