### ISSUE TITLE
[Feature Request] Do not always move view / window when activating a window from the task bar.

### ISSUE THREAD

**Issue by Fan-iX** [directvt/vtm#521]
`vtm` desktop view area is always changed when a partially out-of-view window is activated from the task bar.

This makes it difficult to handle app windows that are larger than the terminal screen - the prompt line is often out of the screen when activating the app window through task bar.

Is it possible not to adjust view area on a single click on the task bar entry?

**Comment by o-sdn-o** [comment]
Indeed, if the app window is larger than the terminal screen, this is a problem, especially if it is something like a tile manager. The current approach to moving/exposing windows needs to be changed.

**Comment by o-sdn-o** [comment]
I've implemented the following logic (https://github.com/directvt/vtm/blob/958db264076b36ff3ae5a6b535ee8c194e26e52c/doc/user-interface.md)
  - RightClick: Toggle taskbar width / Reserved for context menu
  - LeftClick: Set exclusive focus (+restore if minimized)
  - Ctrl+LeftClick: Set/reset group focus
  - DblLeftClick: Jump to window (move viewport)
  - Alt+DblLeftClick: Pull window to viewport center (move window)

What do think?

**Comment by Fan-iX** [comment]
Sensible and works fine.

I would also suggest to have mouse-bindings to move viewport in any cases. Since drag moving is disabled inside an app window with native mouse support (like `htop`), it is difficult to change viewport, move or resize the window when the window has taken up then screen.

The binding could be `Alt-RightDrag` if available.

**Comment by o-sdn-o** [comment]
You could use LeftDrag on taskbar to move viewport.

**Comment by o-sdn-o** [comment]
I added information about LeftDrag on taskbar to tooltips and `user-interface.md`.
