### ISSUE TITLE
Session terminate after pasting

### ISSUE THREAD

**Issue by Fan-iX** [directvt/vtm#533]
I came across a elusive bug in the recent version of `vtm` (confirmed in `v0.9.51`):

When I paste *some kind of* strings in to a vtm session, the session exits and prints out the following error message:

```
 terminate called after throwing an instance of 'std::length_error'
                                                                     what():  basic_string::_M_replace
                                                                                                      Aborted
```
![image](https://github.com/directvt/vtm/assets/61686936/ef28528f-dc4b-46ef-8ae1-128f36cdc51b)

The `vtm` server (daemon) is still alive, and I can reconnect to it through a new session (and the session will crash if I paste again)

A possible string could be `A.1234B.456_AXC50K.abcdefgh.ijkl.axc` or `/home/eusernam/utils/bin/vtm`. There could be much more such strings in different length, and I didn't see a particular pattern.

The bug is quite elusive. It happens every time in a remote `gentoo` server with `bash 5.0.17` or a `Debian` WSL1 distribution with `bash 5.1.4`, and happen sometimes in a `Ubuntu 22.04` WSL2 distribution with `bash 5.1.16` (require some random and elusive combinations of `reset`, `clear`, `^q`, ` ` and paste). Both github releases and local builds are affected.

Seems to be a platform specific client problem. Sessions created from `vtm ssh remote vtm` in windows powershell doesn't show this behavior.

**Comment by o-sdn-o** [comment]
Thanks for the bug report. I'll investigate and fix it.

**Comment by o-sdn-o** [comment]
It seems I found the root cause of the issue.
Regression from commit 39189d4c68ed3677195ff6c8d72df3673c856370.
Variable `b` instead of `a` in `generics.hpp` on line 654.

**Comment by Fan-iX** [comment]
Well, the bug seems to be is fixed in my WSL1 `Debian` distribution now, but not in my remote `gentoo` server.

The problem seems to be introduced in `v0.9.28` (in which bracketed-paste is broken) and `v0.9.29` (in which the crash happens).

In that server, when I connect a `v0.9.28` client to a `v0.9.29` server, and paste `directvt/vtm`, I'll get `direc~directvt/vtm`; If I paste `A.1234B.456_AXC50K.abcdefgh.ijkl.axc`, I'll get one of the following:

```
A.12~A.1234B.456                                                                                                                               
A.1234B.456_AXC50K.abcdefgh.ij~A.1234B.456_AXC50K.abcdefgh.ijkl.axc
A.12~A.1234B.456_AXC50K.abc
A.12~A.1234B.456_AXC50K.abc
A.1234B.456~A.1234B.456_AXC
A.12~A.1234B.456_AXC
A.1234B.456_AXC50K.abc~A.1234B.456_AXC50K.abcdefgh.ij
A.12~A.1234B.456
A.12~A.1234B.456
A.12~A.1234B.456_AXC
```

And when I connect with a `v0.9.29` client, it crashes.

**Comment by Fan-iX** [comment]
> Do I understand correctly that paste does not work for remote `gentoo` server with version vtm v0.9.52 on both the client and the server? 

Yes, crash is still happening in a `v0.9.52` client connecting to a `v0.9.52` server.

I try to figure out in which version the bug was introduced, so I tried a variable of versions.

 - In `v0.9.28(cilent) -> v0.9.28(server)`, paste is completely broken.
 - In `v0.9.29(cilent) -> v0.9.29(server)` and versions after, paste leads to session crash.
 - In `v0.9.28(cilent) -> v0.9.29(server)`, pasting `A.1234B.456_AXC50K.abcdefgh.ijkl.axc` or `/home/eusernam/utils/bin/vtm` gives paste strings of different lengths in that server, this seems to be the cause of the crash in versions after.

I'm glad to collect run logs or crash reports in that environment if it's not reproducible to you. Just tell me what to do.

By the way, It seems that all Linux releases are double-archived - I got a `vtm_linux_x86_64.tar` instead of a simple `vtm` after compressing `vtm_linux_x86_64.zip`

**Comment by o-sdn-o** [comment]
I need to know what platform your client and server are using, and what terminal you are using.

> By the way, It seems that all Linux releases are double-archived - I got a vtm_linux_x86_64.tar instead of a simple vtm after compressing vtm_linux_x86_64.zip

We have to archive this way due to GitHub Actions limitations (https://github.com/actions/upload-artifact#zip-archives).

**Comment by o-sdn-o** [comment]
> I try to figure out in which version the bug was introduced, so I tried various versions

There may be other regressions related to the elimination of Warning messages (#519). There was a lot of refactoring there. It is very likely that I made some other typos there.

**Comment by Fan-iX** [comment]
> I need to know what platform your client and server (gentoo) are running on and what terminal you are using to connect.

It is a `5.6.14-gentoo-x86_64` Linux distribution running on Intel x86_64 CPU.

I did some new tests on connections between different platforms and terminals

| `vtm` client | `vtm` daemon | `vtm` client launched in windows terminal | `vtm` client launched in powershell (console host) | `vtm` client launched in DirectVT window in `vtm.exe v0.9.52` in windows terminal |
|---|---|---|---|---|
| `vtm v0.9.52 Linux` in `gentoo` | `vtm v0.9.52 Linux` in `gentoo` | crash | fine | paste distorted*, won't crash | 
|  `vtm.exe v0.9.52 Windows` | `vtm v0.9.52 Linux` in `gentoo` | fine | fine |  |

\* for example, I got 
```
A.123439;53;13mB.456_AXC50K35;53;13m.abcdefgh.ijkl.axc          
A.1234B.456_AXC50K.abcdefgh.ijkl.axc                              
A.1234B.456_AXC50K.35;53;13mabcdefgh.ijkl.axc                     
A.1234B.456_AXC50K35;53;13m.abcdefgh.ijkl.axc                     
A.1234B.456_AXC50K.35;53;13mabcdefgh.ijkl.axc                     
A.1234B.456_AXC39;53;13m39;53;13m50K35;53;13m.abcdefgh.ijkl.axc
```
after pasting `A.1234B.456_AXC50K.abcdefgh.ijkl.axc` for 6 times in bash

**Comment by o-sdn-o** [comment]
I've got instant repro 👌

https://github.com/directvt/vtm/assets/11535558/16f138e3-00c8-4591-9376-f1518cbc7e4e

**Comment by o-sdn-o** [comment]
It seems I fixed this issue 🙂.

**Comment by Fan-iX** [comment]
It works now.
Thank you.
