### ISSUE TITLE
Project logo / icon

### ISSUE THREAD

**Issue by KillyMXI** [directvt/vtm#541]
I'm looking what icon I can set for the Windows Terminal profile of VTM to better distinguish it among others.
Currently, VTM doesn't seem to contain any usable asset.

(Side note: why I'm using it when I can use WT itself - mainly as a console host I can disconnect and reconnect.)

**Comment by o-sdn-o** [comment]
We can add something like this
![image](https://github.com/directvt/vtm/assets/11535558/b47f9483-0157-45bb-8d8d-acc35fec81c0)

**Comment by o-sdn-o** [comment]
or
![image](https://github.com/directvt/vtm/assets/11535558/280884b2-6e5a-4d25-b1c0-b1c81db20ab4)

**Comment by KillyMXI** [comment]
Between these two, I'd take the sharper one.

But I don't think either one is any good. The project needs a designers help.

**Comment by o-sdn-o** [comment]
Currently the repository logo is a 2x2 pixel image: 
![image](https://github.com/directvt/vtm/assets/11535558/28e9f6aa-2b1e-453c-b88e-81b579ce90f9)

GitHub stretches it with interpolation, so both options can be (with and without interpolation)

**Comment by o-sdn-o** [comment]
> The project needs a designers help.

You are totally right.

**Comment by o-sdn-o** [comment]
The selected logo that is used now is due to the fact that it should be displayed both in text mode and in graphic mode.

**Comment by o-sdn-o** [comment]
Two squares are like two windows on the desktop.

**Comment by KillyMXI** [comment]
> The selected logo that is used now is due to the fact that it should be displayed both in text mode and in graphic mode.

Good point that it should be representable in pseudo graphics.

**Comment by KillyMXI** [comment]
I made this file for my needs:

![vtm](https://github.com/directvt/vtm/assets/13851064/06dff56c-dbc9-4787-8a6f-5607f950a860)

(64x64 PNG with transparency)
