### ISSUE TITLE
Different exit code styles between UNIX and NT

### ISSUE THREAD

**Issue by Vosjedev** [directvt/vtm#557]
On windows (NT) likes, the exit codes are in hexadecimal: `0x7f` but on unix we use integers: `127`. Vtm's terminal always shows it's exit code in hexadecimal, which can be confusing for unix users (like me XD).

![image](https://github.com/directvt/vtm/assets/100359465/4ae4c88a-de68-44b1-aece-cb67841ebfb8)

My suggested solution would be to use integer exit codes when on unix (so linux, bsd, but also mac, etc) instead.
No pressure at all behind this, I don't see the popup that often.

**Comment by o-sdn-o** [comment]
Thanks for the feedback. I agree, this is important to maintain consistency in a terminal environment. I'll make it consistent with the platform.
