### ISSUE TITLE
Maintaining the "don't wrap configuration"

### ISSUE THREAD

**Issue by hansalemaos** [directvt/vtm#574]
First, I want to thank you for your great tool. It's the only way that I found to visualize big pandas DataFrames in the Terminal.  
But I have a little problem: 

When I call print(df) from my Python script and run it, everything works perfectly.  
But when I start working in interactive Python mode, it wraps the DataFrame every time when __str__ or __repr__ is called.  
It is possible to unwrap it easily, but it's really a pain unwrapping big DataFrames all the time.  

Here is a short video to show what I mean:
https://www.youtube.com/watch?v=bf8AxbrUrEw

My question is: 
Is there a setting that I can change to keep the "unwrapped lines configuration", or a way to quickly unwrap a bunch of lines?

**Comment by hansalemaos** [comment]
Thanks for your fast feedback! I will try that in a couple of minutes and give you feedback! Keep up the great work!

**Comment by o-sdn-o** [comment]
Example for python:
```
print('\033[12:2pUnwrapped teeeeeeeeeeeeeeeext')
```

**Comment by hansalemaos** [comment]
Working!! Awesome! Now I'll find out the best way to do that automatically. Thx very much!!
