### ISSUE TITLE
vtm does not work on ubuntu 20.04 since the version 9.84.

### ISSUE THREAD

**Issue by ludetie** [directvt/vtm#600]
Hello,

Vtm does not work on ubuntu 20.04 since the version 9.84.
Version 9.83 is ok.
Apps are not clickable anymore and vtm has to be killed via "Sigkill" because "Disconnect" and "Shutdown" are also not clickable.

Thank you for your work.

Regards,

**Comment by o-sdn-o** [comment]
Thanks for the feedback, I'll fix it.
